[env:rak4631_stable_var]
extends = nrf52840_base
board = wiscore_rak4631
board_check = true
build_flags = ${nrf52840_base.build_flags} 
  -Ivariants/rak4631_stable_var 
  -D RAK_4631
  -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m4/fpv4-sp-d16-hard"
  -L "${platformio.libdeps_dir}/${this.__env__}/SparkFun BMV080 Arduino Library/src/cortex-m4"
  -DGPS_POWER_TOGGLE ; comment this line to disable triple press function on the user button to turn off gps entirely.
  -DEINK_DISPLAY_MODEL=GxEPD2_213_BN
  -DEINK_WIDTH=250
  -DEINK_HEIGHT=122
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
  -DCONFIG_NRF_APPROTECT_DISABLE=1
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/rak4631_stable_var> +<mesh/eth/> +<mesh/api/> +<mqtt/>
lib_deps = 
  ${nrf52840_base.lib_deps}
  ${networking_base.lib_deps}
  melopero/Melopero RV3028@^1.1.0
  https://github.com/RAKWireless/RAK13800-W5100S.git#1.0.2
  rakwireless/RAKwireless NCP5623 RGB LED library@^1.0.2
  https://github.com/RAKWireless/RAK12034-BMX160.git#dcead07ffa267d3c906e9ca4a1330ab989e957e2
